### ISSUE TITLE
CRAN failure...

### ISSUE THREAD

**Issue by ajschumacher** [ajschumacher/rjstat#21]
> Dear maintainer,
>
> Please see the problems shown on
> <https://cran.r-project.org/web/checks/check_results_rjstat.html>.
>
> Please correct before 2022-03-09 to safely retain your package on CRAN.
>
> The CRAN Team

<img width="723" alt="Screen Shot 2022-03-06 at 1 48 44 PM" src="https://user-images.githubusercontent.com/1071322/156937647-f08aedfc-e06c-4936-a09c-87233818464f.png">

**Comment by ajschumacher** [comment]
It's only failing on the dev ones; I think I'll wait and see whether this remains a problem before I try to track down a dev version of R that it's failing for...

Status: Maybe a bug?

**Comment by ajschumacher** [comment]
(Maybe this is #20 showing up, and we can use the solution mentioned there...)

**Comment by olangsrud** [comment]
I am the maintainer of [package PxWebApiData ](https://cran.r-project.org/package=PxWebApiData)which depends on rjstat. I have received the mail saying that “Thus, package rjstat is now scheduled for archival on 2022-03-23, and archiving this will necessitate also archiving its CRAN strong reverse dependencies.”.

To avoid archiving of PxWebApiData I have prepared [a version ](https://github.com/statisticsnorway/PxWebApiData/tree/rjstat-archival)were code for the function fromJSONstat is[ copied from rjstat into PxWebApiData](https://github.com/statisticsnorway/PxWebApiData/blob/rjstat-archival/R/fromJSONstat.R):

I have followed the recommendations in CRAN Repository Policy: Where code is copied (or derived) from the work of others (including from R itself), care must be taken that any copyright/license statements are preserved and authorship is not misrepresented. Preferably, an ‘Authors@R’ field would be used with ‘ctb’ roles for the authors of such code.

Therefore, I have now included the fromJSONstat authors,  Aaron Schumacher and Håkon Malmedal, as authors of PxWebApiData with ‘ctb’ roles. 

The original plan was to include fromJSONstat as a non-exported function. But in the last commit, the function is being exported, due to the needs of some users. 

I hope this is an ok solution for you.

**Comment by hmalmedal** [comment]
@ajschumacher I made a fix and uploaded a new version to CRAN in your name. You will be sent an e-mail you must confirm.

**Comment by hmalmedal** [comment]
Reuploaded

**Comment by ajschumacher** [comment]
Success! Thanks @hmalmedal! You're a hero!

"""
Dear maintainer,

thanks, package rjstat_0.4.2.tar.gz is on its way to CRAN.

Best regards,
CRAN teams' auto-check service
Package check result: OK

No changes to worse in reverse depends.
"""

@olangsrud hope that works for you! Sorry for the inconvenience!

**Comment by ajschumacher** [comment]
All resolved; closed #20, closing this too.

**Comment by olangsrud** [comment]
Nice with new CRAN version of rjstat. Then, I keep PxWebApiData as it is.
